In [1]:
pip install openml pandas scikit-learn matplotlib

Collecting openml
  Downloading openml-0.15.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in c:\users\uap-ii-3\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: scikit-learn in c:\users\uap-ii-3\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: matplotlib in c:\users\uap-ii-3\anaconda3\lib\site-packages (3.10.6)
Collecting liac-arff>=2.4.0 (from openml)
  Downloading liac-arff-2.5.0.tar.gz (13 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting xmltodict (from openml)
  Downloading xmltodict-1.0.4-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: requests in c:\users\uap-ii-3\anaconda3\lib\site-packages (from openml) (2.32.5)
Requirement already satisfied: python-dateutil in c:\users\uap-ii-3\anaconda3\lib\site-packages (from openml) (2.9.0.post0)
Requirement already satisfied: scipy>=0.13.3 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from openml) (1.16.3)
Requirement already satisfied: numpy>=1.6.2 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from openml) (2.3.5)
Collecting minio (from openml)
  Downloading minio-7.2.20-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: pyarrow in c:\users\uap-ii-3\anaconda3\lib\site-packages (from openml) (21.0.0)
Requirement already satisfied: tqdm in c:\users\uap-ii-3\anaconda3\lib\site-packages (from openml) (4.67.1)
Requirement already satisfied: packaging in c:\users\uap-ii-3\anaconda3\lib\site-packages (from openml) (25.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: pillow>=8 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: six>=1.5 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from python-dateutil->openml) (1.17.0)
Requirement already satisfied: argon2-cffi in c:\users\uap-ii-3\anaconda3\lib\site-packages (from minio->openml) (21.3.0)
Requirement already satisfied: certifi in c:\users\uap-ii-3\anaconda3\lib\site-packages (from minio->openml) (2025.11.12)
Collecting pycryptodome (from minio->openml)
  Downloading pycryptodome-3.23.0-cp37-abi3-win_amd64.whl.metadata (3.5 kB)
Requirement already satisfied: typing-extensions in c:\users\uap-ii-3\anaconda3\lib\site-packages (from minio->openml) (4.15.0)
Requirement already satisfied: urllib3 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from minio->openml) (2.5.0)
Requirement already satisfied: argon2-cffi-bindings in c:\users\uap-ii-3\anaconda3\lib\site-packages (from argon2-cffi->minio->openml) (25.1.0)
Requirement already satisfied: cffi>=1.0.1 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi->minio->openml) (2.0.0)
Requirement already satisfied: pycparser in c:\users\uap-ii-3\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->minio->openml) (2.23)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from requests->openml) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from requests->openml) (3.11)
Requirement already satisfied: colorama in c:\users\uap-ii-3\anaconda3\lib\site-packages (from tqdm->openml) (0.4.6)
Downloading openml-0.15.1-py3-none-any.whl (160 kB)
Downloading minio-7.2.20-py3-none-any.whl (93 kB)
Downloading pycryptodome-3.23.0-cp37-abi3-win_amd64.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ---------------------------------- ----- 1.6/1.8 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 5.0 MB/s  0:00:00
Downloading xmltodict-1.0.4-py3-none-any.whl (13 kB)
Building wheels for collected packages: liac-arff
  Building wheel for liac-arff (pyproject.toml): started
  Building wheel for liac-arff (pyproject.toml): finished with status 'done'
  Created wheel for liac-arff: filename=liac_arff-2.5.0-py3-none-any.whl size=11781 sha256=af1356a924c7539d6a30217db426cfec943f5fbb7a39f8fba33f35329843d641
  Stored in directory: c:\users\uap-ii-3\appdata\local\pip\cache\wheels\93\f3\5b\658a9bddee916a5f4b84bdc1a4e0fabd22fb17947c2c9542e6
Successfully built liac-arff
Installing collected packages: xmltodict, pycryptodome, liac-arff, minio, openml

   -------- ------------------------------- 1/5 [pycryptodome]
   -------- ------------------------------- 1/5 [pycryptodome]
   -------- ------------------------------- 1/5 [pycryptodome]
   ---------------- ----------------------- 2/5 [liac-arff]
   -------------------------------- ------- 4/5 [openml]
   ---------------------------------------- 5/5 [openml]

Successfully installed liac-arff-2.5.0 minio-7.2.20 openml-0.15.1 pycryptodome-3.23.0 xmltodict-1.0.4
Note: you may need to restart the kernel to use updated packages.

In [2]:
import openml
import pandas as pd

# Загружаем датасет
dataset = openml.datasets.get_dataset(1590)

In [3]:
# Получаем данные
X, y, categorical_indicator, attribute_names = dataset.get_data(
    dataset_format="dataframe",
    target=dataset.default_target_attribute
)

In [11]:
print(categorical_indicator)

[False, True, False, True, False, True, True, True, True, True, False, False, False, True]

In [12]:
print(attribute_names)

['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country']

In [4]:
print("Размер данных:")
print(X.shape)

Размер данных:
(48842, 14)

In [5]:
print("\nПервые 5 строк:")
print(X.head())

Первые 5 строк:
   age  workclass    fnlwgt     education  education-num      marital-status  \
0   25    Private  226802.0          11th              7       Never-married
1   38    Private   89814.0       HS-grad              9  Married-civ-spouse
2   28  Local-gov  336951.0    Assoc-acdm             12  Married-civ-spouse
3   44    Private  160323.0  Some-college             10  Married-civ-spouse
4   18        NaN  103497.0  Some-college             10       Never-married

          occupation relationship   race     sex  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male           0.0           0.0
1    Farming-fishing      Husband  White    Male           0.0           0.0
2    Protective-serv      Husband  White    Male           0.0           0.0
3  Machine-op-inspct      Husband  Black    Male        7688.0           0.0
4                NaN    Own-child  White  Female           0.0           0.0

   hours-per-week native-country
0              40  United-States
1              50  United-States
2              40  United-States
3              40  United-States
4              30  United-States

In [6]:
print("\nИнформация:")
print(X.info())

Информация:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48842 non-null  uint8
 1   workclass       46043 non-null  category
 2   fnlwgt          48842 non-null  float64
 3   education       48842 non-null  category
 4   education-num   48842 non-null  uint8
 5   marital-status  48842 non-null  category
 6   occupation      46033 non-null  category
 7   relationship    48842 non-null  category
 8   race            48842 non-null  category
 9   sex             48842 non-null  category
 10  capital-gain    48842 non-null  float64
 11  capital-loss    48842 non-null  float64
 12  hours-per-week  48842 non-null  uint8
 13  native-country  47985 non-null  category
dtypes: category(8), float64(3), uint8(3)
memory usage: 1.6 MB
None

In [7]:
print("\nЦелевая переменная:")
print(y.value_counts())

Целевая переменная:
class
<=50K    37155
>50K     11687
Name: count, dtype: int64

In [13]:
print(X.head())

   age  workclass    fnlwgt     education  education-num      marital-status  \
0   25    Private  226802.0          11th              7       Never-married
1   38    Private   89814.0       HS-grad              9  Married-civ-spouse
2   28  Local-gov  336951.0    Assoc-acdm             12  Married-civ-spouse
3   44    Private  160323.0  Some-college             10  Married-civ-spouse
4   18        NaN  103497.0  Some-college             10       Never-married

          occupation relationship   race     sex  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male           0.0           0.0
1    Farming-fishing      Husband  White    Male           0.0           0.0
2    Protective-serv      Husband  White    Male           0.0           0.0
3  Machine-op-inspct      Husband  Black    Male        7688.0           0.0
4                NaN    Own-child  White  Female           0.0           0.0

   hours-per-week native-country
0              40  United-States
1              50  United-States
2              40  United-States
3              40  United-States
4              30  United-States

In [14]:
X.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,25,Private,226802.0,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40,United-States
1,38,Private,89814.0,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50,United-States
2,28,Local-gov,336951.0,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40,United-States
3,44,Private,160323.0,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40,United-States
4,18,NaN,103497.0,Some-college,10,Never-married,NaN,Own-child,White,Female,0.0,0.0,30,United-States

In [15]:
import pandas as pd

In [16]:
# 1. Размер данных
print("="*50)
print("Размер данных:")
print(X.shape)

==================================================
Размер данных:
(48842, 14)

In [17]:
# 2. Типы признаков
print("\n" + "="*50)
print("Типы столбцов:")
print(X.dtypes)

==================================================
Типы столбцов:
age                  uint8
workclass         category
fnlwgt             float64
education         category
education-num        uint8
marital-status    category
occupation        category
relationship      category
race              category
sex               category
capital-gain       float64
capital-loss       float64
hours-per-week       uint8
native-country    category
dtype: object

In [18]:
# 3. Пропуски
print("\n" + "="*50)
print("Пропуски:")
print(X.isnull().sum())

==================================================
Пропуски:
age                  0
workclass         2799
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        2809
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     857
dtype: int64

In [19]:
# 4. Целевая переменная
print("\n" + "="*50)
print("Распределение классов:")
print(y.value_counts())

==================================================
Распределение классов:
class
<=50K    37155
>50K     11687
Name: count, dtype: int64

In [20]:
print("\nПроценты:")
print(y.value_counts(normalize=True)*100)

Проценты:
class
<=50K    76.071823
>50K     23.928177
Name: proportion, dtype: float64

In [23]:
print("\nПроценты:")
print(y.value_counts(normalize=True)*100)

Проценты:
class
<=50K    76.071823
>50K     23.928177
Name: proportion, dtype: float64

In [27]:
# 5. Посмотреть первые строки
print("\n" + "="*50)
print("Первые строки:")
X.head()

==================================================
Первые строки:

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,25,Private,226802.0,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40,United-States
1,38,Private,89814.0,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50,United-States
2,28,Local-gov,336951.0,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40,United-States
3,44,Private,160323.0,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40,United-States
4,18,NaN,103497.0,Some-college,10,Never-married,NaN,Own-child,White,Female,0.0,0.0,30,United-States

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression

In [31]:
# Определяем типы признаков
numeric_features = X.select_dtypes(include=['uint8', 'float64']).columns

In [32]:
numeric_features

Index(['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss',
       'hours-per-week'],
      dtype='object')

In [33]:
categorical_features = X.select_dtypes(
    include=['object', 'category']
).columns

In [34]:
print("Числовые:")
print(list(numeric_features))

Числовые:
['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']

In [36]:
print("\nКатегориальные:")
print(list(categorical_features))

Категориальные:
['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']

In [37]:
# Обработка числовых признаков
numeric_transformer = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='median'))
    ]
)