In [1]:
pip install openml pandas scikit-learn matplotlib

Collecting openml
  Downloading openml-0.15.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in c:\users\uap-ii-3\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: scikit-learn in c:\users\uap-ii-3\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: matplotlib in c:\users\uap-ii-3\anaconda3\lib\site-packages (3.10.6)
Collecting liac-arff>=2.4.0 (from openml)
  Downloading liac-arff-2.5.0.tar.gz (13 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting xmltodict (from openml)
  Downloading xmltodict-1.0.4-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: requests in c:\users\uap-ii-3\anaconda3\lib\site-packages (from openml) (2.32.5)
Requirement already satisfied: python-dateutil in c:\users\uap-ii-3\anaconda3\lib\site-packages (from openml) (2.9.0.post0)
Requirement already satisfied: scipy>=0.13.3 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from openml) (1.16.3)
Requirement already satisfied: numpy>=1.6.2 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from openml) (2.3.5)
Collecting minio (from openml)
  Downloading minio-7.2.20-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: pyarrow in c:\users\uap-ii-3\anaconda3\lib\site-packages (from openml) (21.0.0)
Requirement already satisfied: tqdm in c:\users\uap-ii-3\anaconda3\lib\site-packages (from openml) (4.67.1)
Requirement already satisfied: packaging in c:\users\uap-ii-3\anaconda3\lib\site-packages (from openml) (25.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: pillow>=8 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: six>=1.5 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from python-dateutil->openml) (1.17.0)
Requirement already satisfied: argon2-cffi in c:\users\uap-ii-3\anaconda3\lib\site-packages (from minio->openml) (21.3.0)
Requirement already satisfied: certifi in c:\users\uap-ii-3\anaconda3\lib\site-packages (from minio->openml) (2025.11.12)
Collecting pycryptodome (from minio->openml)
  Downloading pycryptodome-3.23.0-cp37-abi3-win_amd64.whl.metadata (3.5 kB)
Requirement already satisfied: typing-extensions in c:\users\uap-ii-3\anaconda3\lib\site-packages (from minio->openml) (4.15.0)
Requirement already satisfied: urllib3 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from minio->openml) (2.5.0)
Requirement already satisfied: argon2-cffi-bindings in c:\users\uap-ii-3\anaconda3\lib\site-packages (from argon2-cffi->minio->openml) (25.1.0)
Requirement already satisfied: cffi>=1.0.1 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi->minio->openml) (2.0.0)
Requirement already satisfied: pycparser in c:\users\uap-ii-3\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->minio->openml) (2.23)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from requests->openml) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from requests->openml) (3.11)
Requirement already satisfied: colorama in c:\users\uap-ii-3\anaconda3\lib\site-packages (from tqdm->openml) (0.4.6)
Downloading openml-0.15.1-py3-none-any.whl (160 kB)
Downloading minio-7.2.20-py3-none-any.whl (93 kB)
Downloading pycryptodome-3.23.0-cp37-abi3-win_amd64.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ---------------------------------- ----- 1.6/1.8 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 5.0 MB/s  0:00:00
Downloading xmltodict-1.0.4-py3-none-any.whl (13 kB)
Building wheels for collected packages: liac-arff
  Building wheel for liac-arff (pyproject.toml): started
  Building wheel for liac-arff (pyproject.toml): finished with status 'done'
  Created wheel for liac-arff: filename=liac_arff-2.5.0-py3-none-any.whl size=11781 sha256=af1356a924c7539d6a30217db426cfec943f5fbb7a39f8fba33f35329843d641
  Stored in directory: c:\users\uap-ii-3\appdata\local\pip\cache\wheels\93\f3\5b\658a9bddee916a5f4b84bdc1a4e0fabd22fb17947c2c9542e6
Successfully built liac-arff
Installing collected packages: xmltodict, pycryptodome, liac-arff, minio, openml

   -------- ------------------------------- 1/5 [pycryptodome]
   -------- ------------------------------- 1/5 [pycryptodome]
   -------- ------------------------------- 1/5 [pycryptodome]
   ---------------- ----------------------- 2/5 [liac-arff]
   -------------------------------- ------- 4/5 [openml]
   ---------------------------------------- 5/5 [openml]

Successfully installed liac-arff-2.5.0 minio-7.2.20 openml-0.15.1 pycryptodome-3.23.0 xmltodict-1.0.4
Note: you may need to restart the kernel to use updated packages.

In [2]:
import openml
import pandas as pd

# Загружаем датасет
dataset = openml.datasets.get_dataset(1590)

In [3]:
# Получаем данные
X, y, categorical_indicator, attribute_names = dataset.get_data(
    dataset_format="dataframe",
    target=dataset.default_target_attribute
)

In [11]:
print(categorical_indicator)

[False, True, False, True, False, True, True, True, True, True, False, False, False, True]

In [12]:
print(attribute_names)

['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country']

In [4]:
print("Размер данных:")
print(X.shape)

Размер данных:
(48842, 14)

In [5]:
print("\nПервые 5 строк:")
print(X.head())

Первые 5 строк:
   age  workclass    fnlwgt     education  education-num      marital-status  \
0   25    Private  226802.0          11th              7       Never-married
1   38    Private   89814.0       HS-grad              9  Married-civ-spouse
2   28  Local-gov  336951.0    Assoc-acdm             12  Married-civ-spouse
3   44    Private  160323.0  Some-college             10  Married-civ-spouse
4   18        NaN  103497.0  Some-college             10       Never-married

          occupation relationship   race     sex  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male           0.0           0.0
1    Farming-fishing      Husband  White    Male           0.0           0.0
2    Protective-serv      Husband  White    Male           0.0           0.0
3  Machine-op-inspct      Husband  Black    Male        7688.0           0.0
4                NaN    Own-child  White  Female           0.0           0.0

   hours-per-week native-country
0              40  United-States
1              50  United-States
2              40  United-States
3              40  United-States
4              30  United-States

In [6]:
print("\nИнформация:")
print(X.info())

Информация:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48842 non-null  uint8
 1   workclass       46043 non-null  category
 2   fnlwgt          48842 non-null  float64
 3   education       48842 non-null  category
 4   education-num   48842 non-null  uint8
 5   marital-status  48842 non-null  category
 6   occupation      46033 non-null  category
 7   relationship    48842 non-null  category
 8   race            48842 non-null  category
 9   sex             48842 non-null  category
 10  capital-gain    48842 non-null  float64
 11  capital-loss    48842 non-null  float64
 12  hours-per-week  48842 non-null  uint8
 13  native-country  47985 non-null  category
dtypes: category(8), float64(3), uint8(3)
memory usage: 1.6 MB
None

In [7]:
print("\nЦелевая переменная:")
print(y.value_counts())

Целевая переменная:
class
<=50K    37155
>50K     11687
Name: count, dtype: int64

In [13]:
print(X.head())

   age  workclass    fnlwgt     education  education-num      marital-status  \
0   25    Private  226802.0          11th              7       Never-married
1   38    Private   89814.0       HS-grad              9  Married-civ-spouse
2   28  Local-gov  336951.0    Assoc-acdm             12  Married-civ-spouse
3   44    Private  160323.0  Some-college             10  Married-civ-spouse
4   18        NaN  103497.0  Some-college             10       Never-married

          occupation relationship   race     sex  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male           0.0           0.0
1    Farming-fishing      Husband  White    Male           0.0           0.0
2    Protective-serv      Husband  White    Male           0.0           0.0
3  Machine-op-inspct      Husband  Black    Male        7688.0           0.0
4                NaN    Own-child  White  Female           0.0           0.0

   hours-per-week native-country
0              40  United-States
1              50  United-States
2              40  United-States
3              40  United-States
4              30  United-States

In [14]:
X.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,25,Private,226802.0,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40,United-States
1,38,Private,89814.0,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50,United-States
2,28,Local-gov,336951.0,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40,United-States
3,44,Private,160323.0,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40,United-States
4,18,NaN,103497.0,Some-college,10,Never-married,NaN,Own-child,White,Female,0.0,0.0,30,United-States

In [15]:
import pandas as pd

In [16]:
# 1. Размер данных
print("="*50)
print("Размер данных:")
print(X.shape)

==================================================
Размер данных:
(48842, 14)

In [17]:
# 2. Типы признаков
print("\n" + "="*50)
print("Типы столбцов:")
print(X.dtypes)

==================================================
Типы столбцов:
age                  uint8
workclass         category
fnlwgt             float64
education         category
education-num        uint8
marital-status    category
occupation        category
relationship      category
race              category
sex               category
capital-gain       float64
capital-loss       float64
hours-per-week       uint8
native-country    category
dtype: object

In [18]:
# 3. Пропуски
print("\n" + "="*50)
print("Пропуски:")
print(X.isnull().sum())

==================================================
Пропуски:
age                  0
workclass         2799
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        2809
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     857
dtype: int64

In [19]:
# 4. Целевая переменная
print("\n" + "="*50)
print("Распределение классов:")
print(y.value_counts())

==================================================
Распределение классов:
class
<=50K    37155
>50K     11687
Name: count, dtype: int64

In [20]:
print("\nПроценты:")
print(y.value_counts(normalize=True)*100)

Проценты:
class
<=50K    76.071823
>50K     23.928177
Name: proportion, dtype: float64

In [23]:
print("\nПроценты:")
print(y.value_counts(normalize=True)*100)

Проценты:
class
<=50K    76.071823
>50K     23.928177
Name: proportion, dtype: float64

In [27]:
# 5. Посмотреть первые строки
print("\n" + "="*50)
print("Первые строки:")
X.head()

==================================================
Первые строки:

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,25,Private,226802.0,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40,United-States
1,38,Private,89814.0,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50,United-States
2,28,Local-gov,336951.0,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40,United-States
3,44,Private,160323.0,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40,United-States
4,18,NaN,103497.0,Some-college,10,Never-married,NaN,Own-child,White,Female,0.0,0.0,30,United-States

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression

In [31]:
# Определяем типы признаков
numeric_features = X.select_dtypes(include=['uint8', 'float64']).columns

In [32]:
numeric_features

Index(['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss',
       'hours-per-week'],
      dtype='object')

In [33]:
categorical_features = X.select_dtypes(
    include=['object', 'category']
).columns

In [34]:
print("Числовые:")
print(list(numeric_features))

Числовые:
['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']

In [36]:
print("\nКатегориальные:")
print(list(categorical_features))

Категориальные:
['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']

In [37]:
# Обработка числовых признаков
numeric_transformer = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='median'))
    ]
)

In [38]:
# Обработка категориальных признаков
categorical_transformer = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('encoder', OneHotEncoder(handle_unknown='ignore'))
    ]
)

In [39]:
# Объединяем
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

In [40]:
# Создаём модель
model = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('classifier', LogisticRegression(max_iter=1000))
    ]
)

In [41]:
# Делим данные
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [42]:
# Обучаем
model.fit(X_train, y_train)

print("Обучение завершено")

Обучение завершено

c:\Users\UAP-II-3\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [43]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

In [44]:
# Предсказания
y_pred = model.predict(X_test)

In [45]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8496263691268298

In [46]:
print("Precision:", precision_score(y_test, y_pred, pos_label='>50K'))

Precision: 0.7229766431287343

In [47]:
print("Recall:", recall_score(y_test, y_pred, pos_label='>50K'))

Recall: 0.5812227074235807

In [48]:
print("F1:", f1_score(y_test, y_pred, pos_label='>50K'))

F1: 0.644396030016945

In [49]:
print("\nConfusion matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion matrix:
[[6969  510]
 [ 959 1331]]

In [50]:
# Создаём модель
model = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('classifier', LogisticRegression(max_iter=1000, class_weight='balanced'))
    ]
)

In [51]:
# Обучаем
model.fit(X_train, y_train)

print("Обучение завершено")

Обучение завершено

c:\Users\UAP-II-3\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [52]:
# Предсказания
y_pred = model.predict(X_test)

In [53]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, pos_label='>50K'))
print("Recall:", recall_score(y_test, y_pred, pos_label='>50K'))
print("F1:", f1_score(y_test, y_pred, pos_label='>50K'))

print("\nConfusion matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.7950660251816972
Precision: 0.5416425679583574
Recall: 0.8179039301310044
F1: 0.651704940848991

Confusion matrix:
[[5894 1585]
 [ 417 1873]]

In [54]:
from sklearn.metrics import precision_score, recall_score

In [59]:
# Вероятности
y_probs = model.predict_proba(X_test)[:, 1]

threshold = 0.7

y_pred_custom = (y_probs > threshold).astype(int)

In [60]:
# Переводим обратно в метки Adult
y_pred_custom = ['>50K' if x == 1 else '<=50K'
                 for x in y_pred_custom]

print("Precision:",
      precision_score(y_test,
                      y_pred_custom,
                      pos_label='>50K'))

print("Recall:",
      recall_score(y_test,
                   y_pred_custom,
                   pos_label='>50K'))

print(confusion_matrix(y_test,
                       y_pred_custom))

Precision: 0.6762164620281946
Recall: 0.6493449781659388
[[6767  712]
 [ 803 1487]]

In [61]:
pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp313-cp313-win_amd64.whl.metadata (1.5 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in c:\users\uap-ii-3\anaconda3\lib\site-packages (from catboost) (3.10.6)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from catboost) (2.3.5)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from catboost) (2.3.3)
Requirement already satisfied: scipy in c:\users\uap-ii-3\anaconda3\lib\site-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in c:\users\uap-ii-3\anaconda3\lib\site-packages (from catboost) (6.3.0)
Requirement already satisfied: six in c:\users\uap-ii-3\anaconda3\lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from matplotlib->catboost) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from matplotlib->catboost) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from matplotlib->catboost) (3.2.5)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\uap-ii-3\anaconda3\lib\site-packages (from plotly->catboost) (2.7.0)
Downloading catboost-1.2.10-cp313-cp313-win_amd64.whl (100.2 MB)
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.5/100.2 MB 2.4 MB/s eta 0:00:42
    --------------------------------------- 1.3/100.2 MB 3.6 MB/s eta 0:00:28
   - -------------------------------------- 3.1/100.2 MB 5.2 MB/s eta 0:00:19
   -- ------------------------------------- 6.0/100.2 MB 7.7 MB/s eta 0:00:13
   --- ------------------------------------ 9.7/100.2 MB 9.9 MB/s eta 0:00:10
   ----- ---------------------------------- 14.2/100.2 MB 12.0 MB/s eta 0:00:08
   ------ --------------------------------- 17.3/100.2 MB 12.7 MB/s eta 0:00:07
   -------- ------------------------------- 21.0/100.2 MB 13.2 MB/s eta 0:00:06
   ---------- ----------------------------- 25.2/100.2 MB 13.9 MB/s eta 0:00:06
   ----------- ---------------------------- 29.6/100.2 MB 14.7 MB/s eta 0:00:05
   ------------- -------------------------- 34.1/100.2 MB 15.2 MB/s eta 0:00:05
   --------------- ------------------------ 38.5/100.2 MB 15.8 MB/s eta 0:00:04
   ----------------- ---------------------- 42.7/100.2 MB 16.2 MB/s eta 0:00:04
   ------------------ --------------------- 47.2/100.2 MB 16.4 MB/s eta 0:00:04
   -------------------- ------------------- 51.6/100.2 MB 16.7 MB/s eta 0:00:03
   ---------------------- ----------------- 56.4/100.2 MB 17.1 MB/s eta 0:00:03
   ------------------------ --------------- 60.3/100.2 MB 17.2 MB/s eta 0:00:03
   ------------------------- -------------- 64.2/100.2 MB 17.3 MB/s eta 0:00:03
   -------------------------- ------------- 67.6/100.2 MB 17.2 MB/s eta 0:00:02
   ---------------------------- ----------- 72.1/100.2 MB 17.5 MB/s eta 0:00:02
   ------------------------------ --------- 76.0/100.2 MB 17.6 MB/s eta 0:00:02
   ------------------------------- -------- 80.0/100.2 MB 17.7 MB/s eta 0:00:02
   --------------------------------- ------ 83.9/100.2 MB 17.7 MB/s eta 0:00:01
   ----------------------------------- ---- 88.1/100.2 MB 17.8 MB/s eta 0:00:01
   ------------------------------------ --- 92.3/100.2 MB 17.9 MB/s eta 0:00:01
   -------------------------------------- - 95.9/100.2 MB 17.9 MB/s eta 0:00:01
   ---------------------------------------  99.6/100.2 MB 18.0 MB/s eta 0:00:01
   --------------------------------------  100.1/100.2 MB 17.9 MB/s eta 0:00:01
   --------------------------------------  100.1/100.2 MB 17.9 MB/s eta 0:00:01
   --------------------------------------  100.1/100.2 MB 17.9 MB/s eta 0:00:01
   ---------------------------------------- 100.2/100.2 MB 16.1 MB/s  0:00:06
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Installing collected packages: graphviz, catboost

   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   ---------------------------------------- 2/2 [catboost]

Successfully installed catboost-1.2.10 graphviz-0.21
Note: you may need to restart the kernel to use updated packages.

In [71]:
import pandas as pd
import openml

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

from catboost import CatBoostClassifier


# =====================================================
# 1. Загрузка данных
# =====================================================

dataset = openml.datasets.get_dataset(1590)

X, y, categorical_indicator, attribute_names = dataset.get_data(
    dataset_format="dataframe",
    target=dataset.default_target_attribute
)

print("=" * 50)
print("Размер данных:")
print(X.shape)


# =====================================================
# 2. Копия данных
# =====================================================

X_cat = X.copy()


# =====================================================
# 3. Поиск категориальных признаков
# =====================================================

categorical_features = X_cat.select_dtypes(
    include=['object', 'category']
).columns

print("\nКатегориальные признаки:")
print(list(categorical_features))


# =====================================================
# 4. Обработка пропусков
# =====================================================

for col in categorical_features:

    # category -> object
    X_cat[col] = X_cat[col].astype(object)

    # заполнение пропусков
    X_cat[col] = X_cat[col].fillna("missing")


# =====================================================
# 5. Индексы категориальных признаков
# =====================================================

cat_features_idx = [
    X_cat.columns.get_loc(col)
    for col in categorical_features
]


print("\nИндексы категориальных признаков:")
print(cat_features_idx)


# =====================================================
# 6. Train / Test
# =====================================================

X_train, X_test, y_train, y_test = train_test_split(
    X_cat,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# =====================================================
# 7. Создание модели
# =====================================================

model = CatBoostClassifier(
    iterations=500,
    learning_rate=0.05,
    depth=6,
    loss_function='Logloss',
    eval_metric='F1',
    verbose=100
)


# =====================================================
# 8. Обучение
# =====================================================

model.fit(
    X_train,
    y_train,
    cat_features=cat_features_idx,
    eval_set=(X_test, y_test),
    early_stopping_rounds=50
)


# =====================================================
# 9. Предсказание
# =====================================================

y_pred = model.predict(X_test)


# =====================================================
# 10. Метрики
# =====================================================

accuracy = accuracy_score(
    y_test,
    y_pred
)

precision = precision_score(
    y_test,
    y_pred,
    pos_label='>50K'
)

recall = recall_score(
    y_test,
    y_pred,
    pos_label='>50K'
)

f1 = f1_score(
    y_test,
    y_pred,
    pos_label='>50K'
)

cm = confusion_matrix(
    y_test,
    y_pred
)


# =====================================================
# 11. Результаты
# =====================================================

print("\n" + "=" * 50)

print("Accuracy:", round(accuracy,4))
print("Precision:", round(precision,4))
print("Recall:", round(recall,4))
print("F1:", round(f1,4))

print("\nConfusion Matrix:")
print(cm)

==================================================
Размер данных:
(48842, 14)

Категориальные признаки:
['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']

Индексы категориальных признаков:
[1, 3, 5, 6, 7, 8, 9, 13]
0:	learn: 0.6394434	test: 0.6418380	best: 0.6418380 (0)	total: 206ms	remaining: 1m 42s
100:	learn: 0.6910075	test: 0.6946341	best: 0.6954401 (99)	total: 5.01s	remaining: 19.8s
200:	learn: 0.7091049	test: 0.7048121	best: 0.7075449 (170)	total: 9.41s	remaining: 14s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.7075449102
bestIteration = 170

Shrink model to first 171 iterations.

==================================================
Accuracy: 0.875
Precision: 0.804
Recall: 0.6317
F1: 0.7075

Confusion Matrix:
[[7071  360]
 [ 861 1477]]

In [72]:
feature_importance = model.get_feature_importance()

importance_df = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': feature_importance
})

importance_df = importance_df.sort_values(
    by='Importance',
    ascending=False
)

print(importance_df)

           Feature  Importance
5   marital-status   26.318073
10    capital-gain   22.803163
0              age   11.969651
11    capital-loss    7.841345
4    education-num    6.904634
12  hours-per-week    6.423108
6       occupation    6.200995
7     relationship    4.395130
3        education    2.515189
1        workclass    1.429389
9              sex    1.284669
8             race    0.731899
13  native-country    0.611624
2           fnlwgt    0.571130

In [73]:
X_new = X_cat.drop(columns=['fnlwgt'])

print(X_new.shape)

(48842, 13)

In [79]:
# =====================================================
# 6. Train / Test
# =====================================================

X_train, X_test, y_train, y_test = train_test_split(
    X_new,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [82]:
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

# ============================================
# Безопасное удаление столбца
# ============================================

X_new = X_cat.drop(
    columns=['fnlwgt'],
    errors='ignore'
)

print("Размер:")
print(X_new.shape)

print("\nКолонки:")
print(X_new.columns.tolist())


# ============================================
# Категориальные признаки
# ============================================

categorical_features = X_new.select_dtypes(
    include=['object', 'category']
).columns

print("\nКатегориальные:")
print(list(categorical_features))


# ============================================
# Индексы категорий
# ============================================

cat_features_idx = [
    X_new.columns.get_loc(col)
    for col in categorical_features
]

print("\nИндексы:")
print(cat_features_idx)


# ============================================
# Train/Test
# ============================================

X_train, X_test, y_train, y_test = train_test_split(
    X_new,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# ============================================
# Модель
# ============================================

model = CatBoostClassifier(
    iterations=500,
    learning_rate=0.05,
    depth=6,
    loss_function='Logloss',
    eval_metric='F1',
    verbose=100
)


# ============================================
# Обучение
# ============================================

model.fit(
    X_train,
    y_train,
    cat_features=cat_features_idx,
    eval_set=(X_test, y_test),
    early_stopping_rounds=50
)


# ============================================
# Предсказание
# ============================================

y_pred = model.predict(X_test)


# ============================================
# Метрики
# ============================================

print("\nAccuracy:",
      round(
          accuracy_score(y_test, y_pred),
          4
      ))

print("Precision:",
      round(
          precision_score(
              y_test,
              y_pred,
              pos_label='>50K'
          ),
          4
      ))

print("Recall:",
      round(
          recall_score(
              y_test,
              y_pred,
              pos_label='>50K'
          ),
          4
      ))

print("F1:",
      round(
          f1_score(
              y_test,
              y_pred,
              pos_label='>50K'
          ),
          4
      ))

print("\nConfusion Matrix:")
print(confusion_matrix(
    y_test,
    y_pred
))

Размер:
(48842, 13)

Колонки:
['age', 'workclass', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country']

Категориальные:
['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']

Индексы:
[1, 2, 4, 5, 6, 7, 8, 12]
0:	learn: 0.6189788	test: 0.6268280	best: 0.6268280 (0)	total: 60.9ms	remaining: 30.4s
100:	learn: 0.6904159	test: 0.6900927	best: 0.6901099 (99)	total: 5.14s	remaining: 20.3s
200:	learn: 0.7084788	test: 0.7050360	best: 0.7053464 (199)	total: 10.6s	remaining: 15.8s
300:	learn: 0.7192188	test: 0.7074862	best: 0.7084430 (292)	total: 15.8s	remaining: 10.5s
400:	learn: 0.7240631	test: 0.7134030	best: 0.7135726 (395)	total: 21s	remaining: 5.19s
499:	learn: 0.7274326	test: 0.7158444	best: 0.7158444 (499)	total: 26s	remaining: 0us

bestTest = 0.7158444023
bestIteration = 499


Accuracy: 0.8774
Precision: 0.8035
Recall: 0.6454
F1: 0.7158

Confusion Matrix:
[[7062  369]
 [ 829 1509]]